### You can disregard this notebook

In [27]:
import numpy as np
import geopandas as gp
import pandas as pd
import datetime as dt

from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# import .py scripts from repo 
import json_to_csv
from json_to_csv import geojson_to_csv

import ts_train_test_split
from ts_train_test_split import uni_selection
from ts_train_test_split import single_split

import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline

In [28]:
from model_validation import model_val

In [29]:
locations = pd.read_csv('Locations.csv', index_col=0)
locations.head()

,lat,lon,Place,p,d,q,P,D,Q,filepath
0,49.0362,-122.3247,"Abbotsford, Canada",3,1,3,1,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...
1,49.0362,-118.4245,"Grand Forks, Canada",7,0,8,0,1,1,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...
2,48.9289,-117.8306,"Northport, WA",6,1,7,2,0,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...
3,48.7835,-122.3357,"Dewey, WA",8,0,6,1,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...
4,48.7826,-121.7994,"Mt. Baker, WA",8,1,8,0,0,2,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...

In [30]:
locations['lon'][0]

-122.3247

In [26]:
empty = pd.DataFrame()
lons = []
lats = []

for row in range(len(locations)):
    lon = locations['lon'][row]
    lat = locations['lat'][row]
    lons.append(lon)
    lats.append(lat)
    
lons = pd.DataFrame([lons]).T
lats = pd.DataFrame([lats]).T
new = pd.concat([lons, lats], keys=['lon', 'lat'], axis=1)
#new

In [8]:
def test_all(locations):
    MSEs = []
    r2s = []
    for row in range(len(locations)):
        MSE, r2 = model_val(locations, sample=row)
        MSEs.append(MSE)
        r2s.append(r2)
    MSEs = pd.DataFrame([MSEs]).T
    r2s = pd.DataFrame([r2s]).T
    results = pd.concat([MSEs, r2s], keys=['MSE', 'r2'], axis=1)
    return(results)

In [15]:
results = test_all(locations)
results

/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:997: UserWarning: Non-stationary starting seasonal autoregressive Using zeros as starting parameters.
  warn('Non-stationary starting seasonal autoregressive'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'

/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/cbenstead/miniconda3/envs/SERF/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)

         MSE        r2
           0         0
0   0.005196  0.393463
1   0.003308  0.617231
2   0.005505  0.546679
3   0.003690  0.593348
4   0.004682  0.468024
5   0.003606  0.602567
6   0.003135  0.741865
7   0.003992  0.560085
8   0.003449  0.619905
9   0.005012  0.377941
10  0.002153  0.817822
11  0.002714  0.763334
12  0.006058  0.248129
13  0.003293  0.591311
14  0.004938  0.387111
15  0.002746  0.715403
16  0.002861  0.703538
17  0.003121  0.612684
18  0.007226  0.103203
19  0.002504  0.788187
20  0.005903  0.267425
21  0.002175  0.769150
22  0.001809  0.847071
23  0.005376  0.337284
24  0.008174 -0.007530
25  0.001902  0.839179
26  0.003754  0.612882

In [16]:
results.head()

        MSE        r2
          0         0
0  0.005196  0.393463
1  0.003308  0.617231
2  0.005505  0.546679
3  0.003690  0.593348
4  0.004682  0.468024

In [18]:
results.columns = results.columns.droplevel(1)

In [19]:
results

         MSE        r2
0   0.005196  0.393463
1   0.003308  0.617231
2   0.005505  0.546679
3   0.003690  0.593348
4   0.004682  0.468024
5   0.003606  0.602567
6   0.003135  0.741865
7   0.003992  0.560085
8   0.003449  0.619905
9   0.005012  0.377941
10  0.002153  0.817822
11  0.002714  0.763334
12  0.006058  0.248129
13  0.003293  0.591311
14  0.004938  0.387111
15  0.002746  0.715403
16  0.002861  0.703538
17  0.003121  0.612684
18  0.007226  0.103203
19  0.002504  0.788187
20  0.005903  0.267425
21  0.002175  0.769150
22  0.001809  0.847071
23  0.005376  0.337284
24  0.008174 -0.007530
25  0.001902  0.839179
26  0.003754  0.612882

In [20]:
accuracy = pd.concat([locations, results], axis=1)
accuracy

,lat,lon,Place,p,d,q,P,D,Q,filepath,MSE,r2
0,49.0362,-122.3247,"Abbotsford, Canada",3,1,3,1,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.005196,0.393463
1,49.0362,-118.4245,"Grand Forks, Canada",7,0,8,0,1,1,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.003308,0.617231
2,48.9289,-117.8306,"Northport, WA",6,1,7,2,0,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.005505,0.546679
3,48.7835,-122.3357,"Dewey, WA",8,0,6,1,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.003690,0.593348
4,48.7826,-121.7994,"Mt. Baker, WA",8,1,8,0,0,2,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.004682,0.468024
5,48.5767,-122.9509,"Shaw Island, WA",7,0,7,1,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.003606,0.602567
6,48.5085,-117.3252,"Rudy, WA",8,1,5,1,1,2,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.003135,0.741865
7,48.4093,-123.5716,"Metchosin, Canada",7,1,4,1,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.003992,0.560085
8,48.0139,-123.4453,"Port Angeles, WA",7,1,8,0,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.003449,0.619905
9,47.9735,-122.2038,"Everett, WA",4,0,5,0,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.005012,0.377941
10,47.8695,-118.8001,"Wilbur, WA",2,0,5,1,1,3,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.002153,0.817822
11,47.6748,-117.3698,"Spokane, WA",7,0,7,2,0,3,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.002714,0.763334
12,47.6202,-122.1400,"Bellevue, WA",5,0,6,0,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.006058,0.248129
13,47.6155,-122.2917,"Seattle, WA",6,1,1,1,1,1,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.003293,0.591311
14,47.5590,-122.7195,"Gorst, WA",7,0,2,1,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.004938,0.387111
15,47.5053,-121.8406,"Snoqualmie, WA",5,0,7,2,1,3,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.002746,0.715403
16,47.4189,-120.3032,"Wenatchee, WA",6,0,6,3,0,3,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.002861,0.703538
17,47.3855,-122.1983,"Kent, WA",7,0,5,2,1,3,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.003121,0.612684
18,47.2402,-122.4345,"Tacoma, WA",1,0,7,0,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.007226,0.103203
19,47.1095,-119.2320,"Moses Lake, WA",6,0,7,1,0,1,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.002504,0.788187
20,47.0347,-122.8630,"Olympia, WA",2,0,5,0,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.005903,0.267425
21,46.4134,-117.0293,"Lewiston, ID",8,1,1,0,1,3,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.002175,0.769150
22,46.2199,-119.0837,"Kennewick, WA",5,0,8,0,1,1,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.001809,0.847071
23,46.1704,-123.7804,"Navy Heights, OR",4,0,5,0,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.005376,0.337284
24,46.1514,-122.8191,"Kelso, WA",0,0,6,0,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.008174,-0.007530
25,46.0562,-118.3476,"Walla Walla, WA",6,0,7,2,0,2,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.001902,0.839179
26,45.4969,-122.5938,"Portland, OR",6,0,8,3,0,3,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.003754,0.612882

In [24]:
accuracy.to_csv('model-accuracy.csv', index=False)

In [25]:
everything = pd.read_csv('model-accuracy.csv')

In [26]:
everything.head()

,lat,lon,Place,p,d,q,P,D,Q,filepath,MSE,r2
0,49.0362,-122.3247,"Abbotsford, Canada",3,1,3,1,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.005196,0.393463
1,49.0362,-118.4245,"Grand Forks, Canada",7,0,8,0,1,1,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.003308,0.617231
2,48.9289,-117.8306,"Northport, WA",6,1,7,2,0,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.005505,0.546679
3,48.7835,-122.3357,"Dewey, WA",8,0,6,1,1,0,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.003690,0.593348
4,48.7826,-121.7994,"Mt. Baker, WA",8,1,8,0,0,2,NASA/POWER_Point_Monthly_Timeseries_1981_2020_...,0.004682,0.468024